# fly.toml app configuration file generated for wss-pze on 2024-06-20T13:46:43+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wss-pze'
primary_region = 'hkg'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'
  DB_NAME = 'ghgdatabase'
  DB_USER = 'ghgdatabasewssuser'
  DB_PASSWORD = 'wss123456'
  DB_HOST = 'fdaa:9:6d96:0:1::2'
  DB_PORT = '5432'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
